# Generated by Django 5.0.4 on 2024-05-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_delete_production'),
        ('home', '0002_remove_production_price'),
    ]

    operations = [
    ]
