# Generated by Django 5.0.4 on 2024-05-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_merge_20240507_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prices',
            new_name='price',
        ),
    ]
