# Generated by Django 5.0.4 on 2024-05-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_prices_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Production',
        ),
    ]
