# Generated by Django 5.0.4 on 2024-05-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_cartitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
