# Generated by Django 5.0.4 on 2024-05-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
